export type Lang = "fr" | "en";

export const copy = {
  fr: {
    brand: "ALINE PRESTIGE TRAVELS",
    sloganWorld: "ALINE PRESTIGE TRAVELS — Votre monde, notre expertise.",
    sloganSigned: "ALINE PRESTIGE TRAVELS — Votre voyage, signé prestige.",
    sloganShort: "Votre voyage, signé prestige.",
    sloganSteps:
      "Votre destination. Notre expertise. L'excellence en chaque étape.",
    heroEyebrow: "Agence de voyages & affaires internationales",
    heroTitle: "Votre monde, notre expertise.",
    heroLead:
      "Billetterie aérienne, assistance visa et import-export — partout dans le monde, avec la précision d'une maison prestige.",
    ctaAppoint: "Prendre rendez-vous",
    ctaDiscover: "Découvrir les services",
    ctaWhatsapp: "WhatsApp",
    nav: {
      services: "Services",
      tickets: "Billetterie",
      visa: "Visa",
      cargo: "Import-Export",
      world: "Destinations",
      faq: "FAQ",
      book: "Rendez-vous",
    },
    servicesKicker: "Trois métiers",
    servicesTitle: "Un interlocuteur. Trois expertises.",
    servicesLead:
      "Chaque demande est suivie par la même équipe — du premier échange jusqu'à la conclusion.",
    ticketsName: "Billetterie",
    ticketsTag: "Gratuit",
    ticketsDesc:
      "Aller simple, aller-retour ou multi-destinations. Un conseiller vous propose un devis réel — en ligne ou à l'agence.",
    visaName: "Assistance visa",
    visaTag: "30,00 €",
    visaDesc:
      "Préparation de dossier et information visa, pour toutes les destinations. La consultation est payante ; la décision appartient aux autorités.",
    cargoName: "Import-Export",
    cargoTag: "Gratuit",
    cargoDesc:
      "Sourcing, logistique et dépôt de colis à l'agence. L'accompagnement commercial et le dépôt sont sans frais de rendez-vous.",
    learn: "En savoir plus",
    worldKicker: "Couverture mondiale",
    worldTitle: "Europe, Amérique, Asie, Afrique.",
    worldLead:
      "Visas et billets ne se limitent pas à quelques pays. Nous accompagnons vos projets sur les quatre continents.",
    europe: "Europe",
    americas: "Amérique",
    asia: "Asie",
    africa: "Afrique",
    europeEx: "France, Royaume-Uni, Allemagne, Italie, Espagne, Belgique, Suisse, Portugal, Pays-Bas…",
    americasEx: "États-Unis, Canada, Brésil, Mexique, Argentine, Colombie, Chili…",
    asiaEx: "Chine, Inde, Japon, Émirats, Turquie, Singapour, Thaïlande, Corée du Sud…",
    africaEx: "Côte d'Ivoire, Sénégal, Maroc, Afrique du Sud, Ghana, Cameroun, Nigeria, Kenya…",
    worldNote:
      "La faisabilité dépend de votre nationalité, de votre profil et des règles en vigueur. Aucune liste n'est exhaustive : le monde entier est notre terrain.",
    priceKicker: "Tarifs clairs",
    priceTitle: "Ce qui est offert. Ce qui est facturé.",
    priceLead:
      "Les montants s'affichent uniquement en euros. Le paiement en ligne, lorsqu'il est dû, précède la confirmation du rendez-vous.",
    paidTitle: "Payant — 30,00 €",
    paidItems: [
      "Rendez-vous en agence, visio, téléphone ou WhatsApp pour un visa",
      "Demande d'information visa (tourisme, affaires, études, famille, transit)",
    ],
    paidNote:
      "Après le formulaire et le choix de la date, le paiement Stripe de 30,00 € est obligatoire pour confirmer le créneau.",
    freeTitle: "Gratuit",
    freeItems: [
      "Réservation de billet d'avion en ligne",
      "Venir à l'agence pour un billet",
      "Déposer un colis à l'agence (import-export)",
    ],
    howKicker: "Parcours",
    howTitle: "Simple, dans l'ordre.",
    how: [
      {
        n: "01",
        t: "Vous précisez le besoin",
        d: "Visa, billet ou colis — en quelques champs, sans inventaire fictif.",
      },
      {
        n: "02",
        t: "Vous choisissez une date",
        d: "Un créneau souhaité, à confirmer par un conseiller.",
      },
      {
        n: "03",
        t: "Paiement si le service l'exige",
        d: "Pour le visa : 30,00 € en ligne via Stripe, avant confirmation.",
      },
      {
        n: "04",
        t: "Nous vous accompagnons",
        d: "Suivi personnalisé par WhatsApp, e-mail ou à l'agence.",
      },
    ],
    whyKicker: "La maison",
    whyTitle: "L'excellence en chaque étape.",
    why: [
      {
        t: "Interlocuteur unique",
        d: "Vols, visas et colis suivis par la même équipe.",
      },
      {
        t: "Transparence",
        d: "Pas de tarif aérien inventé. Pas de visa promis.",
      },
      {
        t: "Monde entier",
        d: "Europe, Amérique, Asie, Afrique — selon votre projet.",
      },
      {
        t: "Paiement maîtrisé",
        d: "30,00 € TTC affichés en euros, uniquement lorsque c'est dû.",
      },
    ],
    ctaTitle: "Votre voyage, signé prestige.",
    ctaLead:
      "Une demande, un rendez-vous ou un message WhatsApp suffisent pour démarrer.",
    footerLegal:
      "ALINE PRESTIGE TRAVELS. Assistance visa : nous préparons le dossier ; la décision appartient aux autorités. Billetterie : devis personnalisé, sans tarif affiché sans confirmation.",
    hours: "Horaires indicatifs : lun.–sam. 08:30–18:00 (GMT). Un conseiller confirme le créneau.",
    location: "Côte d'Ivoire · Accompagnement international",
    ticketsPage: {
      kicker: "Billetterie aérienne",
      title: "Prenez l'avion. Nous ouvrons la route.",
      lead: "Demande de devis gratuite — en ligne ou directement à l'agence. Aucun paiement n'est requis pour un billet.",
      world: "Des liaisons vers l'Europe, l'Amérique, l'Asie et l'Afrique.",
      online: "Demande en ligne — gratuit",
      agency: "Venir à l'agence — gratuit",
    },
    visaPage: {
      kicker: "Assistance visa",
      title: "Votre dossier, préparé avec exigence.",
      lead: "Information visa et prise de rendez-vous : 30,00 €, payables en ligne avant confirmation. Valable pour l'Europe, l'Amérique, l'Asie et l'Afrique.",
      typesTitle: "Tous les motifs. Tous les continents.",
      payNote:
        "Le parcours : formulaire (informations + date souhaitée) → paiement Stripe 30,00 € → confirmation du rendez-vous.",
      types: [
        {
          t: "Tourisme",
          d: "Séjour privé ou de loisir, quel que soit le continent.",
        },
        {
          t: "Affaires",
          d: "Déplacements professionnels, invitations, sociétés.",
        },
        {
          t: "Études",
          d: "Calendrier de dépôt, pièces et orientation.",
        },
        {
          t: "Famille",
          d: "Visite familiale, regroupement, justificatifs.",
        },
        {
          t: "Transit",
          d: "Autorisations de transit selon l'itinéraire.",
        },
        {
          t: "Préparation",
          d: "Checklist, relecture et organisation du dossier.",
        },
      ],
      disclaimer:
        "Nous ne garantissons pas l'obtention du visa. Nous préparons un dossier complet et cohérent.",
    },
    cargoPage: {
      kicker: "Import-Export",
      title: "Vos colis, votre commerce, sans friction.",
      lead: "Le dépôt de colis à l'agence est gratuit. Sourcing, négoce et logistique sont étudiés sur devis — sans frais de rendez-vous.",
      steps: [
        { t: "Analyse", d: "Besoin, volumes, marchés cibles." },
        { t: "Sourcing", d: "Fournisseurs et filières adaptées." },
        { t: "Négociation", d: "Conditions, délais, qualité." },
        { t: "Achat", d: "Commande et suivi de production." },
        { t: "Logistique", d: "Transport, transit, documents." },
        { t: "Livraison", d: "Réception et clôture." },
      ],
    },
    faqTitle: "Questions fréquentes",
    faq: [
      {
        q: "Comment obtenir un devis pour un vol ?",
        a: "Remplissez le formulaire de billetterie (aller simple, aller-retour ou multi-destinations), en ligne ou en venant à l'agence. Un conseiller vous contacte avec une proposition. Le service est gratuit. Nous n'affichons pas de prix en direct.",
      },
      {
        q: "Pourquoi l'assistance visa est-elle payante ?",
        a: "L'information visa et le rendez-vous associé demandent une étude personnalisée. Le tarif est de 30,00 €, payable en ligne via Stripe avant confirmation de la date. La décision d'octroi du visa appartient exclusivement aux autorités.",
      },
      {
        q: "Quels pays couvrez-vous ?",
        a: "Le monde entier : Europe, Amérique, Asie et Afrique. Chaque dossier dépend de votre nationalité et des exigences en vigueur.",
      },
      {
        q: "Le dépôt de colis est-il payant ?",
        a: "Non. Venir à l'agence pour envoyer un colis est gratuit. Les frais de transport, eux, sont établis au cas par cas.",
      },
      {
        q: "Quand dois-je payer ?",
        a: "Uniquement pour un rendez-vous ou une information visa. Vous remplissez vos informations et la date souhaitée, puis vous réglez 30,00 € en euros via Stripe. Sans paiement, le créneau n'est pas confirmé.",
      },
      {
        q: "Puis-je payer dans une autre devise ?",
        a: "Non. Tous les paiements s'affichent et se règlent en euros (€) uniquement.",
      },
      {
        q: "Le paiement Stripe est-il déjà actif ?",
        a: "Le module Stripe est présenté pour le parcours et les tests. L'encaissement réel sera branché ensuite. Le montant affiché reste 30,00 €.",
      },
      {
        q: "Puis-je vous écrire sur WhatsApp ?",
        a: "Oui. WhatsApp reste le canal le plus direct. Pour un visa, le rendez-vous confirmé passe toutefois par le formulaire et le paiement en ligne.",
      },
    ],
    wizard: {
      titlePaid: "Rendez-vous visa",
      titleTickets: "Demande de billet",
      titleCargo: "Dépôt de colis",
      choose: "Quel service ?",
      stepInfo: "Informations",
      stepDate: "Date",
      stepPay: "Paiement",
      stepDone: "Confirmation",
      firstName: "Prénom",
      lastName: "Nom",
      email: "E-mail",
      phone: "Téléphone",
      nationality: "Nationalité",
      continent: "Continent de destination",
      country: "Pays de destination",
      visaType: "Type de visa",
      tripType: "Type de trajet",
      origin: "Ville / aéroport de départ",
      departure: "Date de départ",
      return: "Date de retour",
      passengers: "Passagers",
      parcel: "Description du colis",
      date: "Date de rendez-vous souhaitée",
      slot: "Créneau",
      mode: "Mode",
      notes: "Précisions",
      notesPh: "Délais, contraintes, références…",
      next: "Continuer",
      back: "Retour",
      submitFree: "Envoyer la demande",
      payCta: "Régler 30,00 €",
      required: "Champ requis",
      emailInvalid: "E-mail invalide",
      channelOnline: "Demande en ligne",
      channelAgency: "Venir à l'agence",
      slotMorning: "Matin — 08:30 à 12:00",
      slotAfternoon: "Après-midi — 14:00 à 18:00",
      modeOffice: "À l'agence",
      modeVisio: "Visioconférence",
      modeWa: "WhatsApp",
      modePhone: "Téléphone",
      visaTourism: "Tourisme",
      visaBusiness: "Affaires",
      visaStudy: "Études",
      visaFamily: "Famille",
      visaTransit: "Transit",
      tripOne: "Aller simple",
      tripReturn: "Aller-retour",
      tripMulti: "Multi-destinations",
      selectContinent: "Choisir un continent",
      paidBanner: "Service payant · 30,00 € · règlement avant confirmation",
      freeBanner: "Service gratuit · aucun paiement requis",
      reviewTitle: "Vérifiez avant de régler",
      reviewFree: "Vérifiez avant d'envoyer",
    },
    pay: {
      title: "Paiement sécurisé",
      amountLabel: "Montant dû",
      currencyNote: "Tous les paiements sont en euros (€) uniquement.",
      card: "Carte bancaire",
      number: "Numéro de carte",
      expiry: "MM / AA",
      cvc: "CVC",
      holder: "Nom sur la carte",
      pay: "Payer 30,00 €",
      processing: "Traitement…",
      secure: "Paiement sécurisé par Stripe",
      demo: "Parcours de test — l'encaissement réel Stripe sera activé ensuite. Aucun débit n'est effectué.",
      error: "Vérifiez les informations de carte pour continuer.",
      brands: "Visa, Mastercard, American Express",
    },
    confirm: {
      title: "C'est confirmé.",
      paidLead: "Votre rendez-vous visa est enregistré. Le règlement de 30,00 € a été simulé pour ce test.",
      freeLead: "Votre demande a bien été transmise. Un conseiller vous recontacte.",
      ref: "Référence",
      amount: "Montant",
      free: "Gratuit",
      next: "Prochaine étape",
      nextPaid: "Un conseiller confirme le créneau et vous envoie la checklist visa.",
      nextFree: "Nous revenons vers vous par e-mail ou WhatsApp.",
      home: "Retour à l'accueil",
      wa: "Écrire sur WhatsApp",
    },
    waDefault:
      "Bonjour ALINE PRESTIGE TRAVELS,\nJe souhaite obtenir des informations sur vos services.",
  },
  en: {
    brand: "ALINE PRESTIGE TRAVELS",
    sloganWorld: "ALINE PRESTIGE TRAVELS — Your world, our expertise.",
    sloganSigned: "ALINE PRESTIGE TRAVELS — Your journey, signed prestige.",
    sloganShort: "Your journey, signed prestige.",
    sloganSteps: "Your destination. Our expertise. Excellence at every step.",
    heroEyebrow: "Travel & international affairs house",
    heroTitle: "Your world, our expertise.",
    heroLead:
      "Air tickets, visa assistance and import-export — worldwide, with the precision of a prestige house.",
    ctaAppoint: "Book an appointment",
    ctaDiscover: "Explore services",
    ctaWhatsapp: "WhatsApp",
    nav: {
      services: "Services",
      tickets: "Tickets",
      visa: "Visa",
      cargo: "Import-Export",
      world: "Destinations",
      faq: "FAQ",
      book: "Appointment",
    },
    servicesKicker: "Three practices",
    servicesTitle: "One counterpart. Three expertises.",
    servicesLead:
      "Every request is followed by the same team — from the first exchange to closing.",
    ticketsName: "Ticketing",
    ticketsTag: "Free",
    ticketsDesc:
      "One-way, return or multi-city. A counsellor sends a real quote — online or at the agency.",
    visaName: "Visa assistance",
    visaTag: "€30.00",
    visaDesc:
      "File preparation and visa information for every destination. The consultation is paid; the decision belongs to the authorities.",
    cargoName: "Import-Export",
    cargoTag: "Free",
    cargoDesc:
      "Sourcing, logistics and parcel drop-off at the agency. Commercial support and drop-off carry no appointment fee.",
    learn: "Learn more",
    worldKicker: "Worldwide coverage",
    worldTitle: "Europe, the Americas, Asia, Africa.",
    worldLead:
      "Visas and tickets are not limited to a handful of countries. We support projects across all four continents.",
    europe: "Europe",
    americas: "Americas",
    asia: "Asia",
    africa: "Africa",
    europeEx: "France, United Kingdom, Germany, Italy, Spain, Belgium, Switzerland, Portugal, Netherlands…",
    americasEx: "United States, Canada, Brazil, Mexico, Argentina, Colombia, Chile…",
    asiaEx: "China, India, Japan, UAE, Turkey, Singapore, Thailand, South Korea…",
    africaEx: "Côte d'Ivoire, Senegal, Morocco, South Africa, Ghana, Cameroon, Nigeria, Kenya…",
    worldNote:
      "Feasibility depends on your nationality, profile and current rules. No list is exhaustive: the whole world is our field.",
    priceKicker: "Clear pricing",
    priceTitle: "What is included. What is billed.",
    priceLead:
      "Amounts are displayed in euros only. When payment is due, it is taken online before the appointment is confirmed.",
    paidTitle: "Paid — €30.00",
    paidItems: [
      "In-person, video, phone or WhatsApp appointment for a visa",
      "Visa information requests (tourism, business, study, family, transit)",
    ],
    paidNote:
      "After the form and preferred date, a €30.00 Stripe payment is required to confirm the slot.",
    freeTitle: "Free",
    freeItems: [
      "Booking an air ticket online",
      "Coming to the agency for a ticket",
      "Dropping a parcel at the agency (import-export)",
    ],
    howKicker: "Path",
    howTitle: "Simple, in order.",
    how: [
      {
        n: "01",
        t: "You state the need",
        d: "Visa, ticket or parcel — a few fields, no fictional inventory.",
      },
      {
        n: "02",
        t: "You choose a date",
        d: "A preferred slot, to be confirmed by a counsellor.",
      },
      {
        n: "03",
        t: "Payment when required",
        d: "For visas: €30.00 online via Stripe, before confirmation.",
      },
      {
        n: "04",
        t: "We stay with you",
        d: "Personal follow-up on WhatsApp, email or at the agency.",
      },
    ],
    whyKicker: "The house",
    whyTitle: "Excellence at every step.",
    why: [
      {
        t: "Single counterpart",
        d: "Flights, visas and parcels handled by the same team.",
      },
      {
        t: "Transparency",
        d: "No invented airfares. No promised visa.",
      },
      {
        t: "Worldwide",
        d: "Europe, the Americas, Asia, Africa — according to your project.",
      },
      {
        t: "Controlled payment",
        d: "€30.00 displayed in euros, only when it is due.",
      },
    ],
    ctaTitle: "Your journey, signed prestige.",
    ctaLead: "A request, an appointment or a WhatsApp message is enough to begin.",
    footerLegal:
      "ALINE PRESTIGE TRAVELS. Visa assistance: we prepare the file; the decision belongs to the authorities. Ticketing: personalised quote, no fare shown without confirmation.",
    hours: "Indicative hours: Mon–Sat 08:30–18:00 (GMT). A counsellor confirms the slot.",
    location: "Côte d'Ivoire · International accompaniment",
    ticketsPage: {
      kicker: "Air ticketing",
      title: "Fly. We open the route.",
      lead: "Free quote request — online or at the agency. No payment is required for a ticket.",
      world: "Connections to Europe, the Americas, Asia and Africa.",
      online: "Online request — free",
      agency: "Visit the agency — free",
    },
    visaPage: {
      kicker: "Visa assistance",
      title: "Your file, prepared with rigour.",
      lead: "Visa information and appointment: €30.00, paid online before confirmation. Valid for Europe, the Americas, Asia and Africa.",
      typesTitle: "Every purpose. Every continent.",
      payNote:
        "The path: form (details + preferred date) → Stripe payment of €30.00 → appointment confirmation.",
      types: [
        { t: "Tourism", d: "Private or leisure stay, on any continent." },
        { t: "Business", d: "Professional travel, invitations, companies." },
        { t: "Study", d: "Filing calendar, documents and guidance." },
        { t: "Family", d: "Family visit, reunification, evidence." },
        { t: "Transit", d: "Transit authorisations along the itinerary." },
        { t: "Preparation", d: "Checklist, review and file organisation." },
      ],
      disclaimer:
        "We do not guarantee that a visa will be granted. We prepare a complete, coherent file.",
    },
    cargoPage: {
      kicker: "Import-Export",
      title: "Your parcels, your trade, without friction.",
      lead: "Parcel drop-off at the agency is free. Sourcing, trading and logistics are quoted case by case — with no appointment fee.",
      steps: [
        { t: "Analysis", d: "Need, volumes, target markets." },
        { t: "Sourcing", d: "Suppliers and suitable channels." },
        { t: "Negotiation", d: "Terms, lead times, quality." },
        { t: "Purchase", d: "Order and production follow-up." },
        { t: "Logistics", d: "Transport, transit, documents." },
        { t: "Delivery", d: "Receipt and closing." },
      ],
    },
    faqTitle: "Frequently asked questions",
    faq: [
      {
        q: "How do I get a flight quote?",
        a: "Fill in the ticketing form (one-way, return or multi-city), online or at the agency. A counsellor contacts you with a proposal. The service is free. We do not display live prices.",
      },
      {
        q: "Why is visa assistance paid?",
        a: "Visa information and the related appointment require a personal study. The fee is €30.00, paid online via Stripe before the date is confirmed. The visa decision belongs solely to the authorities.",
      },
      {
        q: "Which countries do you cover?",
        a: "The whole world: Europe, the Americas, Asia and Africa. Each file depends on your nationality and current requirements.",
      },
      {
        q: "Is parcel drop-off paid?",
        a: "No. Coming to the agency to send a parcel is free. Transport costs are established case by case.",
      },
      {
        q: "When do I pay?",
        a: "Only for a visa appointment or visa information. You fill in your details and preferred date, then pay €30.00 in euros via Stripe. Without payment, the slot is not confirmed.",
      },
      {
        q: "Can I pay in another currency?",
        a: "No. All payments are displayed and settled in euros (€) only.",
      },
      {
        q: "Is Stripe payment already live?",
        a: "The Stripe module is shown for the journey and for tests. Live charging will be connected later. The displayed amount remains €30.00.",
      },
      {
        q: "Can I write on WhatsApp?",
        a: "Yes. WhatsApp remains the most direct channel. For a visa, a confirmed appointment still goes through the form and online payment.",
      },
    ],
    wizard: {
      titlePaid: "Visa appointment",
      titleTickets: "Ticket request",
      titleCargo: "Parcel drop-off",
      choose: "Which service?",
      stepInfo: "Details",
      stepDate: "Date",
      stepPay: "Payment",
      stepDone: "Confirmation",
      firstName: "First name",
      lastName: "Last name",
      email: "Email",
      phone: "Phone",
      nationality: "Nationality",
      continent: "Destination continent",
      country: "Destination country",
      visaType: "Visa type",
      tripType: "Trip type",
      origin: "Departure city / airport",
      departure: "Departure date",
      return: "Return date",
      passengers: "Passengers",
      parcel: "Parcel description",
      date: "Preferred appointment date",
      slot: "Time slot",
      mode: "Mode",
      notes: "Notes",
      notesPh: "Timing, constraints, references…",
      next: "Continue",
      back: "Back",
      submitFree: "Send request",
      payCta: "Pay €30.00",
      required: "Required field",
      emailInvalid: "Invalid email",
      channelOnline: "Online request",
      channelAgency: "Visit the agency",
      slotMorning: "Morning — 08:30 to 12:00",
      slotAfternoon: "Afternoon — 14:00 to 18:00",
      modeOffice: "At the agency",
      modeVisio: "Video call",
      modeWa: "WhatsApp",
      modePhone: "Phone",
      visaTourism: "Tourism",
      visaBusiness: "Business",
      visaStudy: "Study",
      visaFamily: "Family",
      visaTransit: "Transit",
      tripOne: "One-way",
      tripReturn: "Return",
      tripMulti: "Multi-city",
      selectContinent: "Choose a continent",
      paidBanner: "Paid service · €30.00 · payment before confirmation",
      freeBanner: "Free service · no payment required",
      reviewTitle: "Review before paying",
      reviewFree: "Review before sending",
    },
    pay: {
      title: "Secure payment",
      amountLabel: "Amount due",
      currencyNote: "All payments are in euros (€) only.",
      card: "Card",
      number: "Card number",
      expiry: "MM / YY",
      cvc: "CVC",
      holder: "Name on card",
      pay: "Pay €30.00",
      processing: "Processing…",
      secure: "Secured by Stripe",
      demo: "Test journey — live Stripe charging will be enabled later. No card is debited.",
      error: "Please check the card details to continue.",
      brands: "Visa, Mastercard, American Express",
    },
    confirm: {
      title: "Confirmed.",
      paidLead: "Your visa appointment is recorded. The €30.00 payment was simulated for this test.",
      freeLead: "Your request has been sent. A counsellor will get back to you.",
      ref: "Reference",
      amount: "Amount",
      free: "Free",
      next: "Next step",
      nextPaid: "A counsellor confirms the slot and sends the visa checklist.",
      nextFree: "We will come back to you by email or WhatsApp.",
      home: "Back to home",
      wa: "Write on WhatsApp",
    },
    waDefault:
      "Hello ALINE PRESTIGE TRAVELS,\nI would like information about your services.",
  },
} as const;
