/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BilletterieRouteImport } from './routes/billetterie'
import { Route as ConfirmationRouteImport } from './routes/confirmation'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ImportExportRouteImport } from './routes/import-export'
import { Route as RendezVousRouteImport } from './routes/rendez-vous'
import { Route as VisaRouteImport } from './routes/visa'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BilletterieRoute = BilletterieRouteImport.update({
  id: '/billetterie',
  path: '/billetterie',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmationRoute = ConfirmationRouteImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportExportRoute = ImportExportRouteImport.update({
  id: '/import-export',
  path: '/import-export',
  getParentRoute: () => rootRouteImport,
} as any)
const RendezVousRoute = RendezVousRouteImport.update({
  id: '/rendez-vous',
  path: '/rendez-vous',
  getParentRoute: () => rootRouteImport,
} as any)
const VisaRoute = VisaRouteImport.update({
  id: '/visa',
  path: '/visa',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/billetterie': typeof BilletterieRoute
  '/confirmation': typeof ConfirmationRoute
  '/faq': typeof FaqRoute
  '/import-export': typeof ImportExportRoute
  '/rendez-vous': typeof RendezVousRoute
  '/visa': typeof VisaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/billetterie': typeof BilletterieRoute
  '/confirmation': typeof ConfirmationRoute
  '/faq': typeof FaqRoute
  '/import-export': typeof ImportExportRoute
  '/rendez-vous': typeof RendezVousRoute
  '/visa': typeof VisaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/billetterie': typeof BilletterieRoute
  '/confirmation': typeof ConfirmationRoute
  '/faq': typeof FaqRoute
  '/import-export': typeof ImportExportRoute
  '/rendez-vous': typeof RendezVousRoute
  '/visa': typeof VisaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/billetterie'
    | '/confirmation'
    | '/faq'
    | '/import-export'
    | '/rendez-vous'
    | '/visa'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/billetterie'
    | '/confirmation'
    | '/faq'
    | '/import-export'
    | '/rendez-vous'
    | '/visa'
  id:
    | '__root__'
    | '/'
    | '/billetterie'
    | '/confirmation'
    | '/faq'
    | '/import-export'
    | '/rendez-vous'
    | '/visa'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BilletterieRoute: typeof BilletterieRoute
  ConfirmationRoute: typeof ConfirmationRoute
  FaqRoute: typeof FaqRoute
  ImportExportRoute: typeof ImportExportRoute
  RendezVousRoute: typeof RendezVousRoute
  VisaRoute: typeof VisaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billetterie': {
      id: '/billetterie'
      path: '/billetterie'
      fullPath: '/billetterie'
      preLoaderRoute: typeof BilletterieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmation': {
      id: '/confirmation'
      path: '/confirmation'
      fullPath: '/confirmation'
      preLoaderRoute: typeof ConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import-export': {
      id: '/import-export'
      path: '/import-export'
      fullPath: '/import-export'
      preLoaderRoute: typeof ImportExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rendez-vous': {
      id: '/rendez-vous'
      path: '/rendez-vous'
      fullPath: '/rendez-vous'
      preLoaderRoute: typeof RendezVousRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visa': {
      id: '/visa'
      path: '/visa'
      fullPath: '/visa'
      preLoaderRoute: typeof VisaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BilletterieRoute: BilletterieRoute,
  ConfirmationRoute: ConfirmationRoute,
  FaqRoute: FaqRoute,
  ImportExportRoute: ImportExportRoute,
  RendezVousRoute: RendezVousRoute,
  VisaRoute: VisaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
